### PR TITLE
Spawning in occupied shipyard should cause collision

### PR DESCRIPTION
**Pull request by hubcity**
Issue #32 

See comments in code.  Lots of corner cases for this one.

### CODE REVIEW

**Comment by suphoff** [comment]
Why not add the newly spawned ships directly to the list of ships and let the current collision logic handle the rest?

**Comment by hubcity** [comment]
In the 0.3.2 release the spawns are processed after collisions are processed.  I think that is so that a shipyard can't be destroyed and do a spawn in the same turn.

Collisions should be processed on the same turn they are caused.  Currently collisions are processed before spawns and the collisions caused by spawns are ignored until the next turn.  A collision check needs to be done both before and after spawns.  I'm not opposed to a better organization of the code.  Calls to the current collision logic would need to be added after the spawns take place.

**Comment by suphoff** [comment]
I believe with your #39 PR just adding newly spawned ships immediately to the agent (and removing the spawn_move logic) will yield identical results with fewer lines of code.

**Comment by hubcity** [comment]
I don't understand exactly what code change you are suggesting.

The code in 0.3.2 (without this PR) already adds newly spawned ships to the agent without the spawn collision logic.  That code results in [this behavior](https://www.kaggle.com/hubcity/bugs-halite-0-3-2#Occupied-Spawn), which is what I was attempting to fix.

If you have an alternative PR that fixes the unexpected behavior I'm sure kaggle would be happy to get it.

**Comment by hubcity** [comment]
Ok, I had to think about it.  Yes, with the current rules that might work.  But if kaggle makes the currently discussed change to make occupied shipyards invincible, then you might want to keep the logic where spawns are processed after collisions to prevent spawning to fend off an attack.

**Comment by suphoff** [comment]
Thanks! I was not aware of that discussion. In my opinion even after adding the occupied invincible shipyards logic keeping the collision logic in one place would simplify things.
( Just a suggestion - thanks for the PRs! )

**Comment by harrisse** [comment]
Thanks for the PR. After reading through I'm wondering if the right fix here is to have spawns, shipyard conversions, and movement to all happen roughly simultaneously and then have collisions all happen afterward -- any thoughts on this approach? We're going to send out a new version shortly with this setup for internal testing, but I'm definitely interested in other perspectives here.

**Comment by hubcity** [comment]
If the rules of halite don't change then the consolidated approach of processing all collisions after all actions which you and @suphoff propose is clearly better (and I think equivalent to this PR in terms of gameplay).

However if the rules change so that occupied shipyards are invincible then the timing of when spawns are processed will make a difference.  The consolidated approach would allow an agent to spawn a ship to protect an unoccupied shipyard in danger of being attacked (because all collisions will happen after spawns).  The current approach of processing spawns after movement collisions would not allow a spawn to protect a shipyard (because the shipyard would be destroyed before the spawn was processed).  A [comment](https://www.kaggle.com/c/halite/discussion/150937#847339) on the discussion forum from @myles-oneill suggests that he is thinking about processing spawns after movement collisions.  I don't know which would be better in terms of gameplay, but they would certainly be different.

On the other hand if rules change in a different way (like forcing a successful shipyard attack to require two enemy ships) then the consolidated approach sounds better again.

**Comment by hubcity** [comment]
I just looked at your recent commits.  In particular, that you are processing spawns before collisions and that you are processing ship collisions before shipyard collisions.  That's so much cleaner to implement and keeps the rules easy to explain.

**Comment by suphoff** [comment]
@hubcity: The IDs of newly spawned ships and newly converted shipyards can be collected as a set. This set can then be used to limit/modify collision rules for these shipd/yards.

@harrisse: Explaining/verifying movement rules in simultaneous movement games is tricky. The (roughly) simultaneously movement/conversion/spawn approach followed by collision detection rules may be the easiest to explain.
A small framework for running the interpreter for a single step from a predefined state (small 2x2 or 3x3 boards) and actions would be great for documenting expected behavior and could serve as a unit test.

**Comment by harrisse** [comment]
@hubcity As you saw I ended up merging in your ideas here in a different way (with some alternate logic tweaks). I think I'm happy with where we've ended up but wanted to check in with you before I close out this PR -- is there stuff in this PR that you believe is worth merging in given the current state of Halite?

**Comment by harrisse** [comment]
@suphoff Nice idea on the mini board unit tests, I don't know that we'll have time for those before launch but agreed that explaining the rules and edge cases is critically important. We're working with Alexis on the learn team to put together some beginner tutorials which include gifs and images of the relevant edge cases that we're hoping should make the important bits of logic pretty clear.

**Comment by hubcity** [comment]
@harrisse You can close this PR.  I don't believe it adds anything to the current Halite.

**Pull request closed without merging**
