### PR TITLE
Embed player names in video replay

### PR DESCRIPTION
**Pull request by qstanczyk**

### CODE REVIEW

**Comment by harrisse** [comment]
For the format, we'll likely want to provide team name, team id, and submission id for each agent since there isn't a specific agent name field that we publicly expose, and since the format is defined in json we should use camelCase for naming for these specific properties. I'm working on the backend PR today and the format so far is looking like `--info '{"agents": [{"submissionId": 1234567, "teamId": 9998887, "teamName": "Test Team"}, ...]}'` if that helps.

**Comment by harrisse** [comment]
I put together a PR for the backend changes for this component so we should be good here once your front end changes are complete.

**Comment by harrisse** [comment]
Update on format: I chatted with DJ and team ids can become stale due to team merges over time so we instead want to include the episode id rather than the submission id and team id and we'll add a new route to look up the submission from the episode id and index on the backend.

**Comment by qstanczyk** [comment]
One problem I guess is that the game is played between 2 teams and it would be good to know from the video which team is which. If we can't embed team's name in the video then I guess we will have to present this information somewhere close to the link to display / download video. WDYT?

**Comment by harrisse** [comment]
@qstanczyk Can the video not consume information from the info field? I assumed it could look at all fields in the replay file? And to clarify on my comment above, we'd include episode id *and* team name on the info.

**Comment by qstanczyk** [comment]
What I meant is that video is rendered at the time of playing the game between 2 contestants, so if team rename happens afterwards it will not be reflected in the video.

**Comment by qstanczyk** [comment]
Updated this PR, but we can talk about details during the meeting, I guess it will be faster.

**Pull request merged**
