### PR TITLE
added myScore and opponentScore to observation

### PR DESCRIPTION
**Pull request by YBiryukov**

### CODE REVIEW

**Review by harrisse — CHANGES_REQUESTED** [review]
Thanks for the PR!

Since `opponentScore == -myScore` I think we should just offer a single field for your agent's reward. Can you rename the field to `reward` as well to stay consistent with the naming of the `tieRewardThreshold` field?

Could you also update the RPS JSON schema to explain the new props, and add a test to ensure they're set correctly from both agents' perspectives?

Otherwise this looks good!

**Comment by YBiryukov** [comment]
Shouldn't [here](https://github.com/Kaggle/kaggle-environments/blob/392ed9a4fa421f96f087dfa9c3c998864894dc48/kaggle_environments/envs/rps/rps.py#L17) be the same line for `player2`?
`player2.observation.step = step`

**Comment by harrisse** [comment]
@YBiryukov No, `step` is a shared parameter ([see here](https://github.com/Kaggle/kaggle-environments/blob/392ed9a4fa421f96f087dfa9c3c998864894dc48/kaggle_environments/envs/rps/rps.json#L46)) so it only needs to be specified on the first observation and is automatically copied into other observations before they're passed to agents, this means that the field only appears once in the replay file, which is only trivially useful here but becomes more important for environments like halite where the board state is reasonably large.

**Comment by harrisse** [comment]
Thanks for the updates! This will go out in the next release of `kaggle-environments` (likely early next week).

**Review by harrisse — COMMENTED** [review]
LGTM

**Pull request merged**
