### PR TITLE
Update lux s3 with new game parameters + bug fixes

### PR DESCRIPTION
**Pull request by StoneT2000**

### CODE REVIEW

**Comment by StoneT2000** [comment]
Apologies, the number of changes is a bit big since it also includes some major fixes/changes for batched stepping (without changing game rules) which is just for the ML players.

**Comment by bovard** [comment]
Make sure `sh docker/build_cpu.sh` passes, I'm seeing some errors on the unit tests

**Comment by bovard** [comment]
https://github.com/Kaggle/kaggle-environments/pull/293 to fix the unit test

**Review by bovard — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
